apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: /var/lib/jenkins/workspace/test-automate-k8s/agrawalram/nodeapp:${DOCKER_TAG}
        ports:
        - containerPort: 80
