apiVersion: v1 
kind: Pod
metadata:
  name: nodeapp
  labels: 
  app: nodeapp
spec:
  replicas: 2  
  containers:
    - name: nodeapp
      image: username/application-name:tagVersion 
      ports:
      - containerPort: 8000 
